dataset:
  root_path: ../data/mnih

hypers:
  model_name: 'densenet121'
  batch_size: 64
  learning_rate: 0.0001
  num_epochs: 5
  num_classes: 4
  metrics: [ 'loss', 'accuracy', 'f1', 'precision', 'recall' ]
  checkpoint_save_path: './checkpoints/best'